[package]
name = "mini-chain"
version = "0.1.0"
edition = "2024"

[dependencies]
time = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
sha2 = "*"
console = "*"
inquire = "0.9.1"
anyhow = "1.0.100"
tabled = "0.20.0"
indicatif = "0.18.3"
